### ISSUE TITLE
Add PubExchange integration to the article page template

### ISSUE THREAD

**Issue by jonuy** [shinetext/torch#12]
This is manually getting added to the end of every article:

```
<div class="pubexchange_module" id="pubexchange_below_content" data-pubexchange-module-id="2323"></div>

<script>(function(w, d, s, id) {
 w.PUBX=w.PUBX || {pub: "shine_text", discover: false, lazy: true};
 var js, pjs = d.getElementsByTagName(s)[0];
 if (d.getElementById(id)) return;
 js = d.createElement(s); js.id = id; js.async = true;
 js.src = "//main.pubexchange.com/loader.min.js";
 pjs.parentNode.insertBefore(js, pjs);
}(window, document, "script", "pubexchange-jssdk"));</script>
```

I think it's safe now to bring this into the main template.

It's also requested that this section display below the author section. The current template has it rendering above the author.

For the time being, as we're in dev, this module will show up twice. And there will just need to be a transition period we go through pre-launch where we're removing this module from each article that has it.

**Comment by kaladin9017** [comment]
Added to the end of the article template, below author info. 

Ad-block needs to be disabled for the module to show up.
