### ISSUE TITLE
Incorrect robots.txt file in production

### ISSUE THREAD

**Issue by jonuy** [shinetext/torch#120]
Related to #108

https://advice.shinetext.com/robots.txt

Is incorrectly disallowing crawlers on all domains. Code changes were made and the deploy logs suggest that it should be posting the correct one. But the old incorrect one meant for staging with `Disallow: /` still remains.

**Comment by kaladin9017** [comment]
@jonuy 

Chatted with someone from Netlify no luck. The only advice from them is 
```
Not sure why you don't just commit a robots.txt that has what you want in it?
```
I explained its part of the production build script and we were logging the contents of the robots file.

**Comment by jonuy** [comment]
😐  Alright, in that case, let's just try that -- remove the script that creates the robots.txt from the build process and just check-in a robots.txt file and see what happens.

**Comment by kaladin9017** [comment]
Aye Aye. I'm working on a possible solution using Hugo. WIll make a PR soon.
