### ISSUE TITLE
Ensure content and framework updates can be deployed to a production environment

### ISSUE THREAD

**Issue by jonuy** [shinetext/torch#7]
Also on Netlify. Not sure, but ideally it can be configured under the same Netlify-site but use different URLs to distinguish between what's staging and what's production.

**Comment by kaladin9017** [comment]
When we get to pushing to production, we can create a separate deploy on netlify connected to a production branch of torch repo.

**Comment by jonuy** [comment]
There's a `releases` branch now on this repository to indicate our production version. And a 2nd project's been setup on Netlify to deploy on commits to the `releases` branch.
